server:
  service:
    type: NodePort
    nodePort: 30090
  resources:
    limits:
      cpu: 750m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

alertmanager:
  enabled: false  # Disable if not needed

pushgateway:
  enabled: false  # Disable if not needed
