apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-set
  namespace: argocd
spec:
  generators:
    - git:
        # Removed the repoURL to skip GitOps workflow
        revision: HEAD
        directories:
          - path: model-api
  template:
    metadata:
      name: model-api
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      source:
        repository: docker.io/sameerasandeepa/devopsengineer-assignment-api-gateway   # Point to the docker registry
        targetRevision: v1.0  # Specify version/tag here
        chart: ""
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
