replicaCount: 1

image:
  repository: docker.io/sameerasandeepa/devopsengineer-assignment-api-gateway
  pullPolicy: Always
  tag: v2

service:
  type: ClusterIP
  port: 8001


serviceAccount:
  create: true
  name: "gateway-service-account"
  
ingress:
  enabled: false

autoscaling:
  enabled: true  # Set this to true or false based on your requirement
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80